baseURL = 'https://wisarmy.github.io/'
languageCode = 'zh'
title = '遇一只傻喵'
theme = "hugo-book"

defaultContentLanguage = 'zh'
#[languages]
#[languages.zh]
  #languageName = 'Chinese'
  #contentDir = 'content'
  #weight = 1
#[languages.en]
  #languageName = 'English'
  #contentDir = 'content'
  #weight = 2
